spring.application.name=BookInventoryManagement
spring.datasource.url=jdbc:mysql://10.10.181.153:3306/book
spring.datasource.username=bim_devteam
spring.datasource.password=maetved_mib
spring.jpa.generate-ddl=true
server.port=8085
logging.level.org.springframework.jpa=DEBUG
logging.level.org.springframework=DEBUG
